package com.livpure.safedrink.utils;

import androidx.exifinterface.media.ExifInterface;
import java.util.HashMap;
import org.json.JSONObject;
/* loaded from: classes3.dex */
public class AppConstants {
    public static String ACTUAL_AMOUNT = null;
    public static String AMOUNT = null;
    public static String BALANCE = null;
    public static String EMAIL = null;
    public static String GENDER = null;
    public static boolean HAS_USER_PAID = false;
    public static String HOME_BALANCE = "";
    public static Boolean IS_AUTH_LOGIN = null;
    public static Boolean IS_AUTH_REG = null;
    public static Boolean IS_TOPUP_ALLOWED = null;
    public static JSONObject JSON_MESSAGE = null;
    public static String LITRES = null;
    public static String NEW_PLAN_ID = null;
    public static String PASSWORD = null;
    public static String PERIOD = null;
    public static String PLAN = null;
    public static String PLAN_CHANGED = "N";
    public static int PLAN_ID = 0;
    public static HashMap<String, String> PLAN_MAPPING = null;
    public static String PLAN_NAME = null;
    public static String PLAN_STATUS = null;
    public static String RATE = null;
    public static String RATE_PER_LITRE = null;
    public static String RECHARGE_TYPE = "";
    public static String REFERRAL_CODE = null;
    public static String RPL = null;
    public static String SESSION_KEY = "";
    public static String TOKEN;
    public static int TOTAL_CONSUMED;
    public static String USER_ID;
    public static String USER_NAME;
    public static String USER_PHONE;
    public static String USER_PLAN_ID;
    public static String VALIDITY;
    public static Boolean IS_PLAN_CHANGED_ALLOWED = false;
    public static String CIPHER_MODE = "AES/ECB/NoPadding";
    public static String BEL_ENC_KEY = "3Lw9S2nE0Af8Zl1q";
    public static String BLE_CONFIG_COMMAND = "CMD";
    public static String CONFIG_COMMAND = "ARC+CMD=21,%s,%s,%s,%s~";
    public static String CONFIG_RESET_COMMAND = "ARC+CMD=22~";
    public static String CONFIG_RESET_COMMAND_AIR = "IOT+CMD=15~";
    public static String CONFIG_COMMAND_AIR = "IOT+CMD=14,%s,%s,%s,%s~";
    public static String COMMAND_AIR_POWER_ON = "IOT+CMD=01,%s~";
    public static String COMMAND_AIR_POWER_OFF = "IOT+CMD=02,%s~";
    public static String COMMAND_AIR_MANUL_MODE_ON = "IOT+CMD=03,%s~";
    public static String COMMAND_AIR_AUTO_MODE_ON = "IOT+CMD=04,%s~";
    public static String COMMAND_AIR_SLEEP_MODE_ON = "IOT+CMD=05,%s~";
    public static String COMMAND_AIR_RAPID_MODE_ON = "IOT+CMD=06,%s~";
    public static String COMMAND_AIR_NAGATIVE_ION_ON = "IOT+CMD=07,%s~";
    public static String COMMAND_AIR_NAGATIVE_ION_OFF = "IOT+CMD=08,%s~";
    public static String COMMAND_AIR_CHILD_LOCK_ON = "IOT+CMD=09,%s~";
    public static String COMMAND_AIR_CHILD_LOCK_OFF = "IOT+CMD=10,%s~";
    public static String COMMAND_AIR_FAN_SPEED = "IOT+CMD=11,%s,%s~";
    public static String COMMAND_AIR_SET_COUNTDOWN = "IOT+CMD=12,%s,%s~";
    public static String COMMAND_AIR_REFRESH = "IOT+CMD=13~";
    public static String COMMAND_DISPENSING_ON = "ARC+CMD=04";
    public static String COMMAND_DISPENSING_OFF = "ARC+CMD=05";
    public static String COMMAND_COLD_DISPENSING_ON = "ARC+CMD=08";
    public static String COMMAND_COLD_DISPENSING_OFF = "ARC+CMD=09";
    public static String COMMAND_HOT_WATER = "ARC+CMD=02,%s";
    public static String COMMAND_WARM_WATER = "ARC+CMD=01,%s";
    public static String COMMAND_TDS_SETTING = "ARC+CMD=03,%s";
    public static String COMMAND_BOTTLE_DISINFECTION_ON = "ARC+CMD=11";
    public static String COMMAND_BOTTLE_DISINFECTION_OFF = "ARC+CMD=12";
    public static String COMMAND_HEATER_ON = "ARC+CMD=06";
    public static String COMMAND_HEATER_OFF = "ARC+CMD=07";
    public static String COMMAND_COOLIN_ON = "ARC+CMD=13";
    public static String COMMAND_COOLIN_OFF = "ARC+CMD=14";
    public static String COMMAND_QUIET_MODE_ON = "ARC+CMD=26";
    public static String COMMAND_QUIET_MODE_OFF = "ARC+CMD=27";
    public static String COMMAND_WATER_GENERATION_ON = "ARC+CMD=24";
    public static String COMMAND_WATER_GENERATION_OFF = "ARC+CMD=25";

    static {
        HashMap<String, String> hashMap = new HashMap<>();
        PLAN_MAPPING = hashMap;
        hashMap.put("5", "Silver");
        PLAN_MAPPING.put("6", "Gold");
        PLAN_MAPPING.put("7", "Platinum");
        PLAN_MAPPING.put("8", "Titanium");
        PLAN_MAPPING.put("1", "Silver");
        PLAN_MAPPING.put(ExifInterface.GPS_MEASUREMENT_2D, "Gold");
        PLAN_MAPPING.put(ExifInterface.GPS_MEASUREMENT_3D, "Platinum");
        PLAN_MAPPING.put("4", "Titanium");
    }
}
